name = "Infestation"
author = "mxxntype"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80976fffe08aaac5acd74f7f99d3e46f2f266504a495ebceb7c9653528ad47f0"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
